# Permalinks
permalink:           pretty

# Setup
title:               NÓ COMPLETO WAVES PLATFORM!
tagline:             Alugue suas WAVES e receba recompensas!
description:         O lease proof of stake (LPOS) permite que os detentores de WAVES lucrem usando seus saldos para proteger a rede, mantendo o controle total de seus fundos!
url:                 https://waves.one
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Wallison Alves
  url:               https://twitter.com/wall_is_on
  email:             wallisonalvesdeoliveira@zoho.com

# Custom vars
version:             1.0.0
